//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\NXOPEN\备份\1\BlockStyler1.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: zihan
//              Version: NX 2306
//              Date: 07-16-2026  (Format: mm-dd-yyyy)
//              Time: 13:09 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "BlockStyler1.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(BlockStyler1::theSession) = NULL;
UI *(BlockStyler1::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
BlockStyler1::BlockStyler1()
{
    try
    {
        // Initialize the NX Open C++ API environment
        BlockStyler1::theSession = NXOpen::Session::GetSession();
        BlockStyler1::theUI = UI::GetUI();
        theDlxFileName = "1.dlx";
        theDialog = BlockStyler1::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &BlockStyler1::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &BlockStyler1::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &BlockStyler1::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &BlockStyler1::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &BlockStyler1::dialogShown_cb));

        // 初始化状态变量
        moveMode = 1; // 默认复制
        startPt = NXOpen::Point3d(0,0,0);
        endPt = NXOpen::Point3d(0,0,0);
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
BlockStyler1::~BlockStyler1()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    BlockStyler1 *theBlockStyler1 = NULL;
    try
    {
        theBlockStyler1 = new BlockStyler1();
        // The following method shows the dialog immediately
        theBlockStyler1->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theBlockStyler1 != NULL)
    {
        delete theBlockStyler1;
        theBlockStyler1 = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse BlockStyler1::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void BlockStyler1::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void BlockStyler1::dialogShown_cb()
{
    try
    {
        // 设置默认选中"复制"模式（与 UI 截图一致）
        PropertyList* props0 = button0->GetProperties();
        PropertyList* props01 = button01->GetProperties();
        if (moveMode == 1) // 复制
        {
            props0->SetLogical("Value", false);
            props01->SetLogical("Value", true);
        }
        else // 移动
        {
            props0->SetLogical("Value", true);
            props01->SetLogical("Value", false);
        }
        delete props0;
        delete props01;

        // 更新选择对象计数
        UpdateSelectionCount();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//功能：执行移动或复制操作
//------------------------------------------------------------------------------
int BlockStyler1::apply_cb()
{
    int errorCode = 0;
    try
    {
        // 1. 获取选中的对象
        std::vector<tag_t> bodyTags;
        if (!GetSelectedBodies(bodyTags))
        {
            BlockStyler1::theUI->NXMessageBox()->Show("以点选择移动和复制",
                NXOpen::NXMessageBox::DialogTypeWarning, "请先选择要操作的对象。");
            return 1;
        }

        // 2. 获取起始点
        PropertyList* ptProps = point0->GetProperties();
        NXOpen::Point3d pickedStart = ptProps->GetPoint3d("Value");
        delete ptProps;
        NXOpen::Point3d effectiveStart = CalculatePointByType(enum0, pickedStart);

        // 3. 获取结束点
        ptProps = point01->GetProperties();
        NXOpen::Point3d pickedEnd = ptProps->GetPoint3d("Value");
        delete ptProps;
        NXOpen::Point3d effectiveEnd = CalculatePointByType(enum01, pickedEnd);

        // 4. 计算平移向量
        double dx = effectiveEnd.X - effectiveStart.X;
        double dy = effectiveEnd.Y - effectiveStart.Y;
        double dz = effectiveEnd.Z - effectiveStart.Z;

        // 如果向量为零，提示
        if (fabs(dx) < 0.0001 && fabs(dy) < 0.0001 && fabs(dz) < 0.0001)
        {
            BlockStyler1::theUI->NXMessageBox()->Show("以点选择移动和复制",
                NXOpen::NXMessageBox::DialogTypeWarning, "起始点和结束点相同，没有位移。");
            return 1;
        }

        // 5. 创建变换矩阵（平移矩阵）
        double matrix[4][4] = {
            {1, 0, 0, dx},
            {0, 1, 0, dy},
            {0, 0, 1, dz},
            {0, 0, 0, 1}
        };

        // 6. 执行操作
        if (moveMode == 0) // 移动
        {
            // 直接对选中的体应用变换
            int nBodies = (int)bodyTags.size();
            std::vector<tag_t> objTags;
            for (int i = 0; i < nBodies; i++)
            {
                objTags.push_back(bodyTags[i]);
            }
            UF_CALL(UF_MODL_transform_objects(objTags.data(), nBodies, matrix));
        }
        else // 复制
        {
            // 先复制体，再移动复制体
            int nBodies = (int)bodyTags.size();
            for (int i = 0; i < nBodies; i++)
            {
                tag_t newBodyTag = NULL_TAG;
                UF_CALL(UF_MODL_copy_body(bodyTags[i], &newBodyTag));
                if (newBodyTag != NULL_TAG)
                {
                    tag_t objToMove[1] = { newBodyTag };
                    UF_CALL(UF_MODL_transform_objects(objToMove, 1, matrix));
                }
            }
        }

        // 刷新图形窗口
        UF_CALL(UF_MODL_update());
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//功能：响应控件值变化
//------------------------------------------------------------------------------
int BlockStyler1::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == button0)
        {
            // 移动按钮被点击
            PropertyList* props = button0->GetProperties();
            bool isSelected = props->GetLogical("Value");
            delete props;
            if (isSelected)
            {
                moveMode = 0; // 切换为移动模式
                PropertyList* props01 = button01->GetProperties();
                props01->SetLogical("Value", false);
                delete props01;
            }
        }
        else if(block == button01)
        {
            // 复制按钮被点击
            PropertyList* props = button01->GetProperties();
            bool isSelected = props->GetLogical("Value");
            delete props;
            if (isSelected)
            {
                moveMode = 1; // 切换为复制模式
                PropertyList* props0 = button0->GetProperties();
                props0->SetLogical("Value", false);
                delete props0;
            }
        }
        else if(block == selection0)
        {
            // 选择对象变更 - 更新显示计数
            UpdateSelectionCount();
        }
        else if(block == point0)
        {
            // 起始点变更 - 存储坐标
            PropertyList* props = point0->GetProperties();
            startPt = props->GetPoint3d("Value");
            delete props;
        }
        else if(block == enum0)
        {
            // 起始点类型变更 - 更新点捕捉方式
            UpdatePointSnapType(enum0, point0);
        }
        else if(block == point01)
        {
            // 结束点变更 - 存储坐标
            PropertyList* props = point01->GetProperties();
            endPt = props->GetPoint3d("Value");
            delete props;
        }
        else if(block == enum01)
        {
            // 结束点类型变更 - 更新点捕捉方式
            UpdatePointSnapType(enum01, point01);
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int BlockStyler1::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        BlockStyler1::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* BlockStyler1::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

//==============================================================================
// 辅助函数实现
//==============================================================================

//------------------------------------------------------------------------------
// 根据枚举类型计算有效点坐标
// enum0 (起始点类型): 0=边线, 1=体中心, 2=面中心
// enum01 (结束点类型): 0=ABS原点, 1=体中心, 2=面中心, 3=O Y0点, 4=O X0点, 5=O Z0点
//------------------------------------------------------------------------------
NXOpen::Point3d BlockStyler1::CalculatePointByType(
    NXOpen::BlockStyler::Enumeration* enumCtrl, NXOpen::Point3d pickPt)
{
    PropertyList* enumProps = enumCtrl->GetProperties();
    int enumValue = enumProps->GetInteger("Value");
    delete enumProps;

    NXOpen::Point3d result = pickPt;

    // 获取选中的体（用于体中心/面中心计算）
    std::vector<tag_t> bodies;
    GetSelectedBodies(bodies);

    // 判断是哪个枚举控件
    // 通过比较指针判断
    if (enumCtrl == enum0)
    {
        // 起始点类型
        switch (enumValue)
        {
            case 0: // 边线 - 使用拾取点本身
                break;
            case 1: // 体中心
                if (!bodies.empty())
                {
                    double massCenter[3];
                    UF_CALL(UF_MODL_ask_mass_props_3d(bodies[0], 1, 0.0, 0.0, 0.0,
                        massCenter, NULL, NULL, NULL, NULL, NULL, NULL));
                    result = NXOpen::Point3d(massCenter[0], massCenter[1], massCenter[2]);
                }
                break;
            case 2: // 面中心 - 使用拾取点，point0 的捕捉已处理
                break;
        }
    }
    else if (enumCtrl == enum01)
    {
        // 结束点类型
        switch (enumValue)
        {
            case 0: // ABS原点
                result = NXOpen::Point3d(0, 0, 0);
                break;
            case 1: // 体中心
                if (!bodies.empty())
                {
                    double massCenter[3];
                    UF_CALL(UF_MODL_ask_mass_props_3d(bodies[0], 1, 0.0, 0.0, 0.0,
                        massCenter, NULL, NULL, NULL, NULL, NULL, NULL));
                    result = NXOpen::Point3d(massCenter[0], massCenter[1], massCenter[2]);
                }
                break;
            case 2: // 面中心 - 使用拾取点
                break;
            case 3: // O Y0点 - 投影到Y=0平面
                result = NXOpen::Point3d(pickPt.X, 0, pickPt.Z);
                break;
            case 4: // O X0点 - 投影到X=0平面
                result = NXOpen::Point3d(0, pickPt.Y, pickPt.Z);
                break;
            case 5: // O Z0点 - 投影到Z=0平面
                result = NXOpen::Point3d(pickPt.X, pickPt.Y, 0);
                break;
        }
    }

    return result;
}

//------------------------------------------------------------------------------
// 获取选择对象中所有 Body 的 tag
//------------------------------------------------------------------------------
bool BlockStyler1::GetSelectedBodies(std::vector<tag_t>& bodies)
{
    bodies.clear();

    PropertyList* selProps = selection0->GetProperties();
    std::vector<NXOpen::TaggedObject*> selectedObjects = selProps->GetTaggedObjectVector("SelectedObjects");
    delete selProps;

    if (selectedObjects.empty())
        return false;

    // 遍历选中的对象，提取 Body
    for (size_t i = 0; i < selectedObjects.size(); i++)
    {
        NXOpen::Body* body = dynamic_cast<NXOpen::Body*>(selectedObjects[i]);
        if (body != NULL)
        {
            bodies.push_back(body->Tag());
        }
    }

    return !bodies.empty();
}

//------------------------------------------------------------------------------
// 更新选择对象计数显示
//------------------------------------------------------------------------------
void BlockStyler1::UpdateSelectionCount()
{
    PropertyList* selProps = selection0->GetProperties();
    std::vector<NXOpen::TaggedObject*> selectedObjects = selProps->GetTaggedObjectVector("SelectedObjects");
    delete selProps;

    // 构造显示字符串
    char countStr[64];
    sprintf(countStr, "选择对象 (%d)", (int)selectedObjects.size());
    PropertyList* labelProps = selection0->GetProperties();
    labelProps->SetString("Label", countStr);
    delete labelProps;
}

//------------------------------------------------------------------------------
// 更新点拾取控件的捕捉类型
//------------------------------------------------------------------------------
void BlockStyler1::UpdatePointSnapType(
    NXOpen::BlockStyler::Enumeration* enumCtrl,
    NXOpen::BlockStyler::SpecifyPoint* pointCtrl)
{
    PropertyList* enumProps = enumCtrl->GetProperties();
    int enumValue = enumProps->GetInteger("Value");
    delete enumProps;

    PropertyList* pointProps = pointCtrl->GetProperties();

    // 先清除所有捕捉类型
    int clearValue = 0;
    pointProps->SetInteger("SnapPointTypesEnabled", clearValue);

    // 根据枚举类型设置不同的捕捉方式
    if (enumCtrl == enum0)
    {
        switch (enumValue)
        {
            case 0: // 边线 - 启用端点和中点捕捉
            {
                int snapFlags = SnapPointTypesEnabled_EndPoint |
                                SnapPointTypesEnabled_MidPoint |
                                SnapPointTypesEnabled_ControlPoint |
                                SnapPointTypesEnabled_Intersection;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
            case 1: // 体中心 - 启用点构造器
            {
                int snapFlags = SnapPointTypesEnabled_PointConstructor |
                                SnapPointTypesEnabled_ArcCenter;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
            case 2: // 面中心 - 启用点构造器和端点
            {
                int snapFlags = SnapPointTypesEnabled_PointConstructor |
                                SnapPointTypesEnabled_PointonSurface |
                                SnapPointTypesEnabled_EndPoint;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
        }
    }
    else if (enumCtrl == enum01)
    {
        switch (enumValue)
        {
            case 0: // ABS原点 - 不需要捕捉
            {
                int snapFlags = 0;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
            case 1: // 体中心
            {
                int snapFlags = SnapPointTypesEnabled_PointConstructor |
                                SnapPointTypesEnabled_ArcCenter;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
            case 2: // 面中心
            {
                int snapFlags = SnapPointTypesEnabled_PointConstructor |
                                SnapPointTypesEnabled_PointonSurface |
                                SnapPointTypesEnabled_EndPoint;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
            case 3: // O Y0点 - 允许任意点拾取
            case 4: // O X0点
            case 5: // O Z0点
            {
                int snapFlags = SnapPointTypesEnabled_Inferred;
                pointProps->SetInteger("SnapPointTypesEnabled", snapFlags);
                break;
            }
        }
    }

    delete pointProps;
}